import mongoose from "mongoose";
const userSchema = new mongoose.Schema({
username:{type:String,
    required:true,
    trim:true
},
email:{
    type:String,
    required:true,
    unique:true,
    trim:true
},
password:{
    type:String,
    required:true,
    select:false
},
bio:{
    type:String
},
profilepic:{type:String,
    default:"",
},
public_id:{
    type:String
},
followers:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"User"
}],
threads:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Post"
}],
replies:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Comment"
}],
reposts:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Post"
}]
},{timestamps:true})
export const userModel = mongoose.model('User',userSchema)